# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cba1909c59e493948c6c4c9141c8350b"
name = "Heidi-Suckling-Hasan"
application_url = "https://sublime-processor-criterion-rail.trycloudflare.com"
embedded = true
handle = "heidi-suckling-hasan"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_files,write_products,write_publications"

[auth]
redirect_urls = [
  "https://sublime-processor-criterion-rail.trycloudflare.com/auth/callback",
  "https://sublime-processor-criterion-rail.trycloudflare.com/auth/shopify/callback",
  "https://sublime-processor-criterion-rail.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://sublime-processor-criterion-rail.trycloudflare.com"
subpath = "shade_space"
prefix = "apps"

[pos]
embedded = false
