# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6dde760b837c6f4fa076de51ab7dde57"
name = "Shade Sail"
application_url = "https://sail.shadespace.com"
embedded = true
handle = "shade-sail"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_files,write_products,write_publications"

[auth]
redirect_urls = [
  "https://sail.shadespace.com/auth/callback",
  "https://sail.shadespace.com/auth/shopify/callback",
  "https://sail.shadespace.com/api/auth/callback"
]

[app_proxy]
url = "https://sail.shadespace.com"
subpath = "shade_space"
prefix = "apps"

[pos]
embedded = false
